In [2]:
import numpy as np
import cvxpy as cp

# 3.1.f Traditional Rock Paper Scissors

In [59]:
# payoff matrix of the rock-paper-scissors game

M = np.array([[0, -1, 1], [1, 0, -1], [-1, 1, 0]])

print(M)
print('Rock = 0, Paper = 1, Scissors = 2')

[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]
Rock = 0, Paper = 1, Scissors = 2


#### Assuming that the row-player’s strategy is to play rock with probability 1, derive the best-response strategy of the column-player 

(i) logical reasoning : the best response strategy of the column player is to play paper with probability 1

In [60]:
Rock, Paper, Scissors = 0, 1, 2

# (ii) solving a linear program

# define the variables
x = cp.Variable(3, nonneg=True)

# define the objective function
obj = cp.Minimize(cp.sum(cp.multiply(M[Rock,:], x)))

# define the constraints
constraints = [cp.sum(x) == 1]

# define the problem
prob = cp.Problem(obj, constraints)

# solve the problem
prob.solve()

# print the solution
print(f'The best response strategy of the *column* player is to play *rock* with probability', round(x.value[Rock], 3))
print(f'The best response strategy of the *column* player is to play *paper* with probability', round(x.value[Paper],3))
print(f'The best response strategy of the *column* player is to play *scissors* with probability', round(x.value[Scissors], 3))
print('')
print(f'The expected payoff of the *column* player is {-round(prob.value, 3)}')

The best response strategy of the *column* player is to play *rock* with probability 0.0
The best response strategy of the *column* player is to play *paper* with probability 1.0
The best response strategy of the *column* player is to play *scissors* with probability 0.0

The expected payoff of the *column* player is 1.0


In [61]:
# construct the Nash strategies of both players and report the expected payoff of the row-player. Interpret your results.

# define the variables
p = cp.Variable((3,1), nonneg=True)
a = cp.Variable((1), nonneg=False)

# define the objective function

obj = cp.Maximize(a)

# define the constraints
constraints = [cp.sum(p) == 1, a <= (p.T@M).T]

# define the problem
prob = cp.Problem(obj, constraints)

# solve the problem
prob.solve()
print(f'Status: {prob.status}\n')

column_player_values = constraints[1].dual_value

# print the solution for the row and colunm player
print( "The best response strategy of the *column* player is to play *rock* with probability", round(p.value[Rock][0], 3))
print( "The best response strategy of the *column* player is to play *paper* with probability", round(p.value[Paper][0],3))
print( "The best response strategy of the *column* player is to play *scissors* with probability", round(p.value[Scissors][0], 3))
print('')
print( "The best response strategy of the *column* player is to play *rock* with probability", round(column_player_values[Rock][0], 3))
print( "The best response strategy of the *column* player is to play *paper* with probability", round(column_player_values[Paper][0],3))
print( "The best response strategy of the *column* player is to play *scissors* with probability", round(column_player_values[Scissors][0], 3))
print('')
print(f'The expected payoff of the *row* player is', np.round(constraints[0].dual_value, 3))
print(f'The expected payoff of the *column* player is', -np.round(constraints[0].dual_value, 3))


Status: optimal

The best response strategy of the *column* player is to play *rock* with probability 0.333
The best response strategy of the *column* player is to play *paper* with probability 0.333
The best response strategy of the *column* player is to play *scissors* with probability 0.333

The best response strategy of the *column* player is to play *rock* with probability 0.333
The best response strategy of the *column* player is to play *paper* with probability 0.333
The best response strategy of the *column* player is to play *scissors* with probability 0.333

The expected payoff of the *row* player is -0.0
The expected payoff of the *column* player is 0.0


# 2.1.g Modified Rock Paper Scissors

In [62]:
# Consider a modified rock-paper-scissors game, where the payoff of the row-player amounts to +2 instead of +1 if she wins by playing rock. 

# define the modified payoff matrix

print("Payoff matrix of the modified rock-paper-scissors game:\n")
M = np.array([[0, -1, 2], [1, 0, -1], [-1, 1, 0]])
print(M)
print('Rock = 0, Paper = 1, Scissors = 2\n')

# define the variables
p = cp.Variable((3,1), nonneg=True)
a = cp.Variable((1), nonneg=False)

# define the objective function

obj = cp.Maximize(a)

# define the constraints
constraints = [cp.sum(p) == 1, a <= (p.T@M).T]

# define the problem
prob = cp.Problem(obj, constraints)

# solve the problem
prob.solve()
print(f'Status: {prob.status}\n')

column_player_values = constraints[1].dual_value

# print the solution for the row and colunm player
print( "The best response strategy of the *column* player is to play *rock* with probability", round(p.value[Rock][0], 3))
print( "The best response strategy of the *column* player is to play *paper* with probability", round(p.value[Paper][0],3))
print( "The best response strategy of the *column* player is to play *scissors* with probability", round(p.value[Scissors][0], 3))
print('')
print( "The best response strategy of the *column* player is to play *rock* with probability", round(column_player_values[Rock][0], 3))
print( "The best response strategy of the *column* player is to play *paper* with probability", round(column_player_values[Paper][0],3))
print( "The best response strategy of the *column* player is to play *scissors* with probability", round(column_player_values[Scissors][0], 3))
print('')
print(f'The expected payoff of the *row* player is', np.round(constraints[0].dual_value, 3))
print(f'The expected payoff of the *column* player is', -np.round(constraints[0].dual_value, 3))

Payoff matrix of the modified rock-paper-scissors game:

[[ 0 -1  2]
 [ 1  0 -1]
 [-1  1  0]]
Rock = 0, Paper = 1, Scissors = 2

Status: optimal

The best response strategy of the *column* player is to play *rock* with probability 0.25
The best response strategy of the *column* player is to play *paper* with probability 0.417
The best response strategy of the *column* player is to play *scissors* with probability 0.333

The best response strategy of the *column* player is to play *rock* with probability 0.333
The best response strategy of the *column* player is to play *paper* with probability 0.417
The best response strategy of the *column* player is to play *scissors* with probability 0.25

The expected payoff of the *row* player is 0.083
The expected payoff of the *column* player is -0.083


## Sanity check :

In [63]:
import nashpy as nash
import numpy as np

A = np.array([[0, -1, 2], [1, 0, -1], [-1, 1, 0]])
B = - A
rps = nash.Game(A, B)
rps

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  2]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -2]
 [-1  0  1]
 [ 1 -1  0]]

In [64]:
eqs = rps.support_enumeration()

eqs = list(eqs)

print("The Nash equilibria are:\n")
print("For the row player: rock : ", np.round(eqs[0][0][0], 3) ,", paper : ", np.round(eqs[0][0][1], 3), ", scissors : ", np.round(eqs[0][0][2], 3))
print("For the column player: rock : ", np.round(eqs[0][1][0], 3) ,", paper : ", np.round(eqs[0][1][1], 3), ", scissors : ", np.round(eqs[0][1][2], 3))

print("the payoff for the row player is : ", np.round(eqs[0][0]@A@eqs[0][1].T, 3))
print("the payoff for the column player is : ", np.round(eqs[0][0]@B@eqs[0][1].T, 3))

The Nash equilibria are:

For the row player: rock :  0.25 , paper :  0.417 , scissors :  0.333
For the column player: rock :  0.333 , paper :  0.417 , scissors :  0.25
the payoff for the row player is :  0.083
the payoff for the column player is :  -0.083
